### ISSUE TITLE
Not working in GNOME 3.32

### ISSUE THREAD

**Issue by Horus125** [BigE/desk-changer#62]
Error message "TypeError: this._construct is not a function"

**Comment by Horus125** [comment]
https://github.com/micheleg/dash-to-dock/issues/877

**Comment by jjgalvez** [comment]
can confirm this is broken with GS 3.32

**Comment by BigE** [comment]
Hi,

The current state of this plugin is not compatible with 3.32 at all. I'm currently working on a rewrite that has been a long time coming. Please, stay tuned for updates.

**Comment by pjpreilly** [comment]
It's still functional since settings are accessible through Tweaks as well as the Gnome Shell Extension.

**Comment by jjgalvez** [comment]
I am going to keep an eye on this project because I really like what you have been doing, but at them moment I have switched to variety,

**Comment by djwyman** [comment]
so it says that it has an error so I uninstalled this plug in yet it was actually still changing my wallpaper until I went in and had to reinstall this plugin and make it stop on gnome 3.32.   So even though it has an error it seems to still work.  keeping an eye out though for the new version when it comes out.

**Comment by curvatura99** [comment]
Well until the new version is released I made my own script for random wallpaper and lockscreen switching. To launch on startup place a desktop file in .config/autostart. Here's the script if anyone wishes to use it:

`#!/bin/bash

IMG=(/usr/share/backgrounds/misc/*)
TMR=(300)

  while true
    do
     sleep $TMR
       RND=(${IMG[RANDOM % ${#IMG[@]}]})
         
         gsettings set org.gnome.desktop.background picture-uri "file://$RND"
         gsettings set org.gnome.desktop.screensaver picture-uri "file://$RND"
  
   done`

Of course change the path to your wallpaper location and change the time to whatever suits you best.

**Comment by nickurak** [comment]
Oddly enough it seems to have started working again since I upgraded to Gnome 3.34 (in Fedora 31 beta)

**Comment by pjpreilly** [comment]
> Oddly enough it seems to have started working again since I upgraded to Gnome 3.34 (in Fedora 31 beta)

Yes it was working but not in the Top Bar but it's back baby!

**Comment by BigE** [comment]
I've kinda dove back in to development again... since I'm rewriting the whole extension to be JS driven, it's just going to take some time. Currently the problem with the existing version is it just isn't ES6 compatible, though it should work beyond that.

I tried hacking together a version that wasn't a complete rewrite, but the daemon moving into the extension caused other issues that were crashing gnome entirely. I need to update the ES6 rewrite branch with my latest changes, but any help to get this completed is welcome!

**Comment by adrinux** [comment]
We'll need an idea of what needs doing if we're going to help @BigE, a little roadmap, which branches to work on etc.

**Comment by BigE** [comment]
@adrinux I would love to provide you with that.. but I am just unable to commit that amount of time, currently. There is a [feature/ES6-rewrite](https://github.com/BigE/desk-changer/tree/feature/ES6-rewrite) branch that I've started already. The daemon itself is, for the most part, already there and working.

What currently needs attention is the UI. There isn't one 😄 That's about the best roadmap I can currently give. I've been trying to get back and pay some attention to this extension... soon!

**Comment by BigE** [comment]
Updating. I've had time and done a lot. The extension is no where near complete... but the daemon and UI are working with a full ES6 rewrite. All work to date is in the develop branch.

### Current Needs
- Preferences - I'm in the middle of a total rewrite of this as well. More to come, help appreciated.
- Debugging - Pull develop, install the extension, use it. I need bug reports, I know there are lots.

**Comment by BigE** [comment]
See release [Version 28](https://github.com/BigE/desk-changer/releases/tag/version-28) for 3.32 support
