### ISSUE TITLE
broker after update of gnome 3.34.2

### ISSUE THREAD

**Issue by zeners** [BigE/desk-changer#66]
after update to 3.34.2 getting the following error (even with current git-branch 87da66c):
TypeError: this.set_icon is not a function

**Comment by BigE** [comment]
Hi @zeners,
Thanks for reporting this. I've found the issue and fixed it. Once I'm able to make another release, this should be resolved for you. You're always welcome to install the extension from github directly. Thanks again!

**Comment by zeners** [comment]
thx for fixing the issue. Now it works again.
